### ISSUE TITLE
Why does MemoryLocation not contain CpuOnly and General Allocation Usage?

### ISSUE THREAD

**Issue by Sprial404** [Traverse-Research/gpu-allocator#35]
The VMA has a option for HOST_VISIBLE and HOST_COHERENT memory types by using CPU only. Otherwise I have to use CPU to GPU which is not what I require.

**Comment by Jasper-Bekkers** [comment]
CpuOnly would be a bit of a misnomer - since all resources allocated through our allocator (and through VMA) are also visible to the device, so we've omitted it on purpose.

The memory that matches those flags that is closest to what you're looking for is GpuToCpu, which asks for HOST_VISBLE | HOST_COHERENT | HOST_CACHED, meaning it's optimized for readback on the CPU.

What is the use-case that you have specifically for CpuOnly?

**Comment by Sprial404** [comment]
Ahh, thank you! That makes sense, I though it was the only setting to have HOST_VISIBLE and HOS_COHERENT to be filled out. I was porting code from VMA over to this crate because VMA rust seems not have active contributions. I was allocating index buffers and vertex buffers. Unrelated to memory settings but would a depth buffer be consider linear for the AllocationCreateDesc?

**Comment by Jasper-Bekkers** [comment]
As a rule of thumb nothing should be marked linear, especially not render targets or depth/stencil targets.

Linear is a niche feature for reading back textures on the CPU.
